name: anthem
description: An open-source digital audio workstation.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  anthem_codegen:
    path: codegen

  args: ^2.6.0
  collection: ^1.17.1
  colorize: ^3.0.0
  crypto: ^3.0.6
  file_picker: ^10.1.9
  flutter_mobx: ^2.3.0
  flutter_shaders: ^0.1.3
  flutter_svg: ^2.0.16
  fuzzywuzzy: ^1.2.0
  mobx: ^2.5.0
  nanoid: ^1.0.0
  provider: ^6.0.2
  vector_math: ^2.1.2

  pointer_lock:
    git:
      url: https://github.com/helgoboss/pointer_lock.git
      ref: 11322c2
  mockito: ^5.4.5
  window_manager: ^0.5.0
  okcolor: ^1.1.0

dev_dependencies:
  analyzer: ^7.7.0
  build_runner: ^2.6.0
  build: ^3.0.0
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.7.2
  source_gen: ^3.0.0

flutter:
  uses-material-design: false

  shaders:
  - assets/shaders/automation_curve.frag

  fonts:
  - family: RobotoMono
    fonts:
    - asset: assets/fonts/RobotoMono.ttf

  assets:
  - assets/engine/

  - assets/icons_old/
  - assets/icons_old/add/
  - assets/icons_old/arranger/
  - assets/icons_old/arranger/clip/
  - assets/icons_old/audio_editor/
  - assets/icons_old/automation_editor/
  - assets/icons_old/bottom_bar/
  - assets/icons_old/channel/
  - assets/icons_old/channel_rack/
  - assets/icons_old/controller_rack/
  - assets/icons_old/device_panel/
  - assets/icons_old/edit/
  - assets/icons_old/instrument_and_effect_rack/
  - assets/icons_old/main/
  - assets/icons_old/main_toolbar/
  - assets/icons_old/misc/
  - assets/icons_old/mixer/
  - assets/icons_old/not_clickable/
  - assets/icons_old/note_editor/
  - assets/icons_old/options/
  - assets/icons_old/scrollbar/
  - assets/icons_old/small/
  - assets/icons_old/tools/
  - assets/icons_old/topbar/

  - assets/icons/
  - assets/icons/add/
  - assets/icons/arranger/
  - assets/icons/audio_editor/
  - assets/icons/automation_editor/
  - assets/icons/bottom_bar/
  - assets/icons/channel_rack/
  - assets/icons/edit/
  - assets/icons/icon/
  - assets/icons/instrument_and_effect_rack/
  - assets/icons/main_toolbar/
  - assets/icons/misc/
  - assets/icons/mixer/
  - assets/icons/note_editor/
  - assets/icons/options/
  - assets/icons/small/
