server:
  headers:
    - name: Cross-Origin-Opener-Policy
      value: same-origin
    - name: Cross-Origin-Embedder-Policy
      value: require-corp
    - name: Cross-Origin-Resource-Policy
      value: same-origin
