name: anthem_codegen
description: Code generation for Anthem
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  analyzer: ^8.2.0
  build: ^4.0.1
  source_gen: ^4.0.1
  flutter_test:
    sdk: flutter
  mobx: ^2.5.0
  collection: ^1.19.1
dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0

  # We don't use this, but the parent Anthem pubspec does, and it has prevented
  # us from upgrading packages in the past. This allows us to run `flutter pub
  # upgrade --major-versions` here without getting package versions that are
  # incompatible with the parent.
  mobx_codegen: ^2.7.2
